[tool.poetry]
name = "timex"
version = "0.1.0"
description = ""
authors = ["Bram <bramiozo@gmail.com>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.10,<3.13"
pandas = "^2.2.2"
tqdm = "^4.66.4"
numpy = "^2.0.0"
scipy = "^1.14.0"
statsmodels = "^0.14.2"
networkx = "^3.3"
dcor = "^0.6"
sktime = "^0.31.0"
scikit-learn = "^1.5.1"
scikit-lego = "^0.9.1"
tslearn = "^0.6.3"
dtaidistance = "^2.3.12"
pymannkendall = "^1.4.3"
tsfresh = "^0.20.2"
cesium = "^0.12.1"
antropy = "^0.1.6"
nolds = "^0.5.2"
fastdtw = "^0.3.4"
pywavelets = "^1.6.0"
torch = "^2.3.1"
matplotlib = "^3.9.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
