[tool.poetry]
name = "timex"
version = "0.1.0"
description = ""
authors = ["Bram <bramiozo@gmail.com>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
pydmd = "^1.0.0"
scipy = "^1.14.1"
tqdm = "^4.66.5"
pandas = "^2.2.2"
statsmodels = "^0.14.2"
networkx = "^3.3"
scikit-learn = "^1.5.1"
scikit-lego = "^0.9.1"
sktime = "^0.32.1"
dtaidistance = "^2.3.12"
tslearn = "^0.6.3"
dcor = "^0.6"
matplotlib = "^3.9.2"
pywavelets = "^1.7.0"
pymannkendall = "^1.4.3"
tsfresh = "0.21.0"
pycatch22 = {path= "./assets/pycatch22-0.4.5-cp312-cp312-win_amd64.whl", develop=false}
antropy = "^0.1.6"
nolds = "^0.6.0"
fastdtw = "^0.3.4"
meegkit = "^0.1.7"
python = ">3.10,<3.13"
numpy = "^1.26.4"
cesium = "^0.12.1"
fairseq = "^0.12.2"
wfdb = ">=4.2.0"
neurokit2 = "^0.2.10"
python-dotenv = "^1.1.0"
torch = {version = "^2.2.2+cu121", source = "pytorch"}
pywavelet = "^0.2.7"
pyarrow = "^19.0.1"


[tool.poetry.group.dev.dependencies]
jupyter = ">=1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"