# -*- coding: utf-8 -*-
"""sax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgJoTMWMMzlIeLmOJ-GxfW5-QsG6OFcf
"""

import wfdb
import tslearn
import pandas as pd
import numpy as np
import math
import json
import scipy as sc
from scipy import signal
import neurokit2 as nk
import matplotlib.pyplot as plt
from tslearn.piecewise import SymbolicAggregateApproximation,OneD_SymbolicAggregateApproximation
from scipy.signal import find_peaks, butter, filtfilt, detrend, savgol_filter, sosfilt
from pathlib import Path
import importlib
from sklearn import preprocessing






class ECGTokenizer:
    def __init__(self, n_segments=100, alphabet_size=300):
        
        self.n_segments = n_segments
        self.alphabet_size = alphabet_size
        self.toks_sax = None
        self.toks_sax_inv = None
        self.toks_ld = None
        self.toks_ld_inv = None
        self.params = None

    def tokenize_sax(self, data):
        his_dat = []
        his_inv_dat = []

        for sig_group in data:
            for sig in sig_group:
                signal1 = sig.reshape(1, -1)
                sax = SymbolicAggregateApproximation(n_segments=self.n_segments, alphabet_size_avg=self.alphabet_size)
                sax_data = sax.fit_transform(signal1)
                his_dat.append(sax_data.reshape(self.n_segments,))
                sax_inv = sax.inverse_transform(sax_data).reshape(-1)
                his_inv_dat.append(sax_inv)

        self.toks_sax = np.array(his_dat)
        self.toks_sax_inv = his_inv_dat
        
        return self.toks_sax, self.toks_sax_inv

    def tokenize_1d_sax(self, data):
        his_dat = []
        his_inv_dat = []
        for sig_group in data:
            for sig in sig_group:
                signal1 = sig.reshape(1, -1)
                ld_sax = OneD_SymbolicAggregateApproximation(n_segments=self.n_segments, alphabet_size_avg=self.alphabet_size, alphabet_size_slope=self.alphabet_size)
                ld_sax_data = ld_sax.fit_transform(signal1)
                his_dat.append(ld_sax_data.reshape(self.n_segments * 2,))
                ld_sax_inv = ld_sax.inverse_transform(ld_sax_data).reshape(len(ld_sax.inverse_transform(ld_sax_data)[0]))
                his_inv_dat.append(ld_sax_inv)

        self.toks_ld = np.array(his_dat)
        self.toks_ld_inv = his_inv_dat
        return self.toks_ld, self.toks_ld_inv
